language: node_js
git:
  depth: 10
node_js:
  - "0.12"
  - "0.10"
  - "4.0.0"
cache:
  bundler: true
  apt: true
  directories:
    - node_modules
notifications:
  email:
    on_success: never
    on_failure: always
sudo: false
